### ISSUE TITLE
sasl.process() fails

### ISSUE THREAD

**Issue by Pustik41** [internetarchive/snakebite-py3#12]
I try to connect to HDFS via AutoConfigClient, but have an error:

**Comment by Pustik41** [comment]
Additional info i use client.ls(["/"]) and it returns generator object HAClient._ha_gen_method.<locals>.wrapped, but if I put it in list list(client.ls(["/"])) get this error

**Comment by Pustik41** [comment]
2020-10-14 05:56:29,403 ERROR indeed.cmdlineutil: Error running tool: Traceback (most recent call last):
  File "/mnt/kubernetes/sandbox/data-governance--change-control-statistics-reporter/lib/python3.6/site-packages/cmdlineutil/__init__.py", line 228, in run
    self._run_impl(*args, **kwargs)
  File "/mnt/kubernetes/sandbox/data-governance--change-control-statistics-reporter/changecontrolstatisticsreporter/imhotepdataset/__main__.py", line 216, in _run_impl
    raise e
  File "/mnt/kubernetes/sandbox/data-governance--change-control-statistics-reporter/changecontrolstatisticsreporter/imhotepdataset/__main__.py", line 211, in _run_impl
    self.build_index()
  File "/mnt/kubernetes/sandbox/data-governance--change-control-statistics-reporter/changecontrolstatisticsreporter/imhotepdataset/__main__.py", line 196, in build_index
    self.get_indexes_sizes()
  File "/mnt/kubernetes/sandbox/data-governance--change-control-statistics-reporter/changecontrolstatisticsreporter/imhotepdataset/__main__.py", line 162, in get_indexes_sizes
    for x in client.ls(['/']):
  File "/mnt/kubernetes/sandbox/data-governance--change-control-statistics-reporter/lib/python3.6/site-packages/snakebite/client.py", line 1549, in wrapped
    yield next(results)
  File "/mnt/kubernetes/sandbox/data-governance--change-control-statistics-reporter/lib/python3.6/site-packages/snakebite/client.py", line 174, in ls
    recurse=recurse):
  File "/mnt/kubernetes/sandbox/data-governance--change-control-statistics-reporter/lib/python3.6/site-packages/snakebite/client.py", line 1223, in _find_items
    fileinfo = self._get_file_info(path)
  File "/mnt/kubernetes/sandbox/data-governance--change-control-statistics-reporter/lib/python3.6/site-packages/snakebite/client.py", line 1351, in _get_file_info
    return self.service.getFileInfo(request)
  File "/mnt/kubernetes/sandbox/data-governance--change-control-statistics-reporter/lib/python3.6/site-packages/snakebite/service.py", line 43, in <lambda>
    rpc = lambda request, service=self, method=method.name: service.call(service_stub_class.__dict__[method], request)
  File "/mnt/kubernetes/sandbox/data-governance--change-control-statistics-reporter/lib/python3.6/site-packages/snakebite/service.py", line 49, in call
    return method(self.service, controller, request)
  File "/mnt/kubernetes/sandbox/data-governance--change-control-statistics-reporter/lib/python3.6/site-packages/google/protobuf/service_reflection.py", line 283, in <lambda>
    self._StubMethod(inst, method, rpc_controller, request, callback))
  File "/mnt/kubernetes/sandbox/data-governance--change-control-statistics-reporter/lib/python3.6/site-packages/google/protobuf/service_reflection.py", line 300, in _StubMethod
    method_descriptor.output_type._concrete_class, callback)
  File "/mnt/kubernetes/sandbox/data-governance--change-control-statistics-reporter/lib/python3.6/site-packages/snakebite/channel.py", line 489, in CallMethod
    self.get_connection(self.host, self.port)
  File "/mnt/kubernetes/sandbox/data-governance--change-control-statistics-reporter/lib/python3.6/site-packages/snakebite/channel.py", line 251, in get_connection
    sasl_connected = self.sasl.connect()
  File "/mnt/kubernetes/sandbox/data-governance--change-control-statistics-reporter/lib/python3.6/site-packages/snakebite/rpc_sasl.py", line 109, in connect
    initiate.token = self.sasl.process()
